--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.7.31.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 16.5.2019. 17:21:55
-- Server version: 11.00.2100
--

-- USE [WLC]
-- GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

DROP TABLE WLC.dbo.Kategorije
GO

CREATE TABLE WLC.dbo.Kategorije (
  SifraKategorije int IDENTITY,
  NazivKategorije nvarchar(20) NULL,
  OdKG float NULL,
  DoKG float NULL,
  Spol nvarchar(1) NULL,
  Kadeti nvarchar(1) NULL
)
ON [PRIMARY]
GO

SET IDENTITY_INSERT WLC.dbo.Kategorije ON
GO
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (1, N'-55', 0, 55, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (2, N'-61', 55.01, 61, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (3, N'-67', 61.01, 67, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (4, N'-73', 67.01, 73, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (5, N'-81', 73.01, 81, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (6, N'-89', 81.01, 89, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (7, N'-96', 89.01, 96, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (8, N'-102', 96.01, 102, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (9, N'-109', 102.01, 109, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (10, N'+109', 109.01, 999, N'M', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (11, N'-45', 0, 45, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (12, N'-49', 45.01, 49, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (13, N'-55', 49.01, 55, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (14, N'-59', 55.01, 59, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (15, N'-64', 59.01, 64, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (16, N'-71', 64.01, 71, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (17, N'-76', 71.01, 76, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (18, N'-81', 76.01, 81, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (19, N'-87', 81.01, 87, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (20, N'87+', 87.01, 999, N'Z', N'N')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (21, N'-49', 0, 49, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (22, N'-55', 49.01, 55, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (23, N'-61', 55.01, 61, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (24, N'-67', 61.01, 67, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (25, N'-73', 67.01, 73, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (26, N'-81', 73.01, 81, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (27, N'-89', 81.01, 89, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (28, N'-96', 89.01, 96, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (29, N'-102', 96.01, 102, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (30, N'102+', 102.01, 999, N'M', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (31, N'-40', 0, 40, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (32, N'-45', 40.01, 45, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (33, N'-49', 45.01, 49, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (34, N'-55', 49.01, 55, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (35, N'-59', 55.01, 59, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (36, N'-64', 59.01, 64, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (37, N'-71', 64.01, 71, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (38, N'-76', 71.01, 76, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (39, N'-81', 76.01, 81, N'Z', N'D')
INSERT WLC.dbo.Kategorije(SifraKategorije, NazivKategorije, OdKG, DoKG, Spol, Kadeti) VALUES (40, N'81+', 81.01, 999, N'Z', N'D')
GO
SET IDENTITY_INSERT WLC.dbo.Kategorije OFF
GO